display = "Gruvbox Light Medium"
variant = "light"

[wezterm]
scheme = "Gruvbox light, medium (base16)"

[nvim]
plugin      = "morhetz/gruvbox"
colorscheme = "gruvbox"
setup = '''
vim.g.gruvbox_contrast_light = 'medium'
'''
