display = "Modus Operandi Tinted"
variant = "light"

[wezterm]
scheme = "Modus-Operandi-Tinted"

[nvim]
plugin      = "miikanissi/modus-themes.nvim"
colorscheme = "modus"
setup = '''
require('modus-themes').setup {
  variants = { modus_operandi = 'tinted' },
}
'''
